[package]
name = "myos"
version = "0.1.0"
edition = "2021"
authors = ["Yulong<baiyulong2009@hotmail.com"]

[dependencies]
bootloader = "0.9.21"
volatile = "0.2.6"
spin = "0.9.2"


[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]
